[package]
name = "neural-network-from-scratch"
version = "0.1.0"
authors = ["Mohammad Rahhal"]
edition = "2021"

[dependencies]
maplit = "1.0.2"
once_cell = "1.13.0"

[dev-dependencies]
assert_matches = "1.5.0"
rstest = "0.15.0"
